export type QwenChatModeId =
  | 'qwen3-max'
  | 'qwen-plus'
  | 'qwen-plus-latest'
  | 'qwen-flash'
  | 'qwen-turbo'
  | 'qwen-turbo-latest'
  | 'qwq-plus'
  | 'qwq-plus-latest'
  | 'qwen-long'
  | 'qwen-long-latest'
  | 'qwen3-omni-flash'
  | 'qwen3-omni-flash-realtime'
  | 'qvq-max'
  | 'qvq-max-latest'
  | 'qwen3-vl-plus'
  | 'qwen3-vl-flash'
  | 'qwen-vl-ocr'
  | 'qwen-vl-ocr-latest'
  | 'qwen-audio-turbo'
  | 'qwen-audio-turbo-latest'
  | 'qwen-math-plus'
  | 'qwen-math-turbo'
  | 'qwen3-coder-plus'
  | 'qwen-mt-plus'
  | 'qwen-deep-research'
  | 'deepseek-v3.2'
  | (string & {})
